name: Generate Snake Contribution Graph

on:
  schedule:
    # Run at 5:00 AM UTC every day
    - cron: "0 5 * * *"

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v3
        with:
          # GitHub user name to read the contribution graph from
          github_user_name: ${{ github.repository_owner }}

          # List of files to generate
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Upload GitHub Snake Graph
        uses: actions/upload-artifact@v2
        with:
          name: contribution-graph
          path: dist
